# docker-compose.yml
version: '3.8'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/AnySearch-0.0.1-SNAPSHOT.jar
    container_name: spring-boot-app
    ports:
      - "8081:8080"
    environment:
      - spring_elasticsearch_uris=http://elasticsearch:9200
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ady_db
      - SPRING_DATASOURCE_USERNAME=any
      - SPRING_DATASOURCE_PASSWORD=any
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - elasticsearch
      - db
    networks:
      - spring-boot-network

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    image: custom-elasticsearch:8.17.6
    container_name: elasticsearch_instance
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      # 사용자 사전 및 동의어 사전 파일을 호스트의 ./searchDictionary/에서 컨테이너의 config/dictionary/로 마운트
      - ./searchDictionary/:/usr/share/elasticsearch/config/dictionary/
      - esdata:/usr/share/elasticsearch/data # 데이터 영속성을 위해 볼륨 사용
    networks:
      - spring-boot-network
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ady_db
      POSTGRES_USER: any
      POSTGRES_PASSWORD: any
    ports:
      - "5433:5432" # 외부 5433, 내부 5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - spring-boot-network # 네트워크 통일

volumes:
  esdata: # Elasticsearch 데이터 볼륨 정의
  dbdata: # PostgreSQL 데이터 볼륨 정의

networks:
  spring-boot-network:
    driver: bridge