# docker-compose.yml
version: '3.8'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/AnySearch-0.0.1-SNAPSHOT.jar
    container_name: spring-boot-app
    ports:
      - "8081:8080"
    environment:
      - spring_elasticsearch_uris=http://elasticsearch:9200
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ady_db
      - SPRING_DATASOURCE_USERNAME=any
      - SPRING_DATASOURCE_PASSWORD=any
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - elasticsearch
      - db
    networks:
      - spring-boot-network # 네트워크 통일

  elasticsearch:
    # Elasticsearch 전용 Dockerfile을 빌드하여 플러그인 설치
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch # Elasticsearch 전용 Dockerfile 사용
    image: custom-elasticsearch:8.17.6 # 빌드된 이미지에 태그 부여 (Kibana 버전과 일치)
    container_name: elasticsearch_instance
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data # 데이터 영속성을 위해 볼륨 사용
      # Dockerfile.elasticsearch에서 사용자 사전을 복사하므로 여기서 볼륨 마운트는 필요 없을 수 있습니다.
      # 만약 런타임에 외부에서 파일을 변경하고 싶다면 마운트 유지.
      # - ./searchDictionary/:/usr/share/elasticsearch/config/dictionary/
    networks:
      - spring-boot-network # 네트워크 통일

  kibana:
    image: kibana:8.17.6 # Elasticsearch와 버전 일치
    container_name: kibana_instance
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - spring-boot-network # 네트워크 통일

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ady_db
      POSTGRES_USER: any
      POSTGRES_PASSWORD: any
    ports:
      - "5433:5432" # 외부 5433, 내부 5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - spring-boot-network # 네트워크 통일

volumes:
  esdata: # Elasticsearch 데이터 볼륨 정의
  dbdata: # PostgreSQL 데이터 볼륨 정의

networks:
  spring-boot-network:
    driver: bridge