version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch_instance
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - spring-boot-network

  # PostgreSQL 서비스
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ady_db
      POSTGRES_USER: any
      POSTGRES_PASSWORD: any
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - spring-boot-network

volumes:
  esdata:
  dbdata:

networks:
  spring-boot-network:
    driver: bridge