version: '3.8'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/AnySearch-0.0.1-SNAPSHOT.jar
    container_name: spring-boot-app
    ports:
      - "8081:8080"
    environment:
      # 변경된 부분: 엘라스틱 노드들 정의(장애시 다른곳 연결하도록 해줌)
      - spring_elasticsearch_uris=http://es01:9200
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ady_db
      - SPRING_DATASOURCE_USERNAME=any
      - SPRING_DATASOURCE_PASSWORD=any
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      # 모든 노드가 준비된 후 구동
      - es01
      - es02
      - es03
      - db
    networks:
      - spring-boot-network

  es01:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    image: custom-elasticsearch:8.17.6
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=my-es-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      # 외부와의 통신은 이 마스터 노드만 담당
      - "9200:9200"
    volumes:
      - ./searchDictionary/:/usr/share/elasticsearch/config/dictionary/
      - esdata01:/usr/share/elasticsearch/data
    networks:
      - spring-boot-network

  es02:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    image: custom-elasticsearch:8.17.6
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=my-es-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./searchDictionary/:/usr/share/elasticsearch/config/dictionary/
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - spring-boot-network

  es03:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    image: custom-elasticsearch:8.17.6
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=my-es-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./searchDictionary/:/usr/share/elasticsearch/config/dictionary/
      - esdata03:/usr/share/elasticsearch/data
    networks:
      - spring-boot-network

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ady_db
      POSTGRES_USER: any
      POSTGRES_PASSWORD: any
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - spring-boot-network

volumes: # 각 노드별로 정의
  esdata01:
  esdata02:
  esdata03:
  dbdata:

networks:
  spring-boot-network:
    driver: bridge