version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch_instance
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - spring-boot-network
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: any_db
      POSTGRES_USER: any
      POSTGRES_PASSWORD: any
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - spring-boot-network

volumes:
  esdata:
  dbdata:

networks:
  spring-boot-network: # 서비스 간 통신을 위한 사용자 정의 네트워크
    driver: bridge